name: advent-of-code
version: 0.1.0.0
license: MIT

ghc-options:
  - -Wall
  - -Werror
  - -O2

dependencies:
  - base

executables:
  day-01-exe:
    main: Main.hs
    source-dirs: app/Day01
    dependencies:
      - advent-of-code
  day-02-exe:
    main: Main.hs
    source-dirs: app/Day02
    dependencies:
      - advent-of-code
  day-03-exe:
    main: Main.hs
    source-dirs: app/Day03
    dependencies:
      - advent-of-code
  day-04-exe:
    main: Main.hs
    source-dirs: app/Day04
    dependencies:
      - advent-of-code
  day-05-exe:
    main: Main.hs
    source-dirs: app/Day05
    dependencies:
      - advent-of-code

library:
  source-dirs: src
  dependencies:
    - bytestring
    - bytestring-conversion
    - containers
    - cryptohash-md5
    - text

tests:
  test:
    main: Spec.hs
    source-dirs: test
    when:
      - condition: false
        other-modules: Paths_advent_of_code
    dependencies:
      - advent-of-code
      - hspec
      - hspec-discover
      - containers
