name: advent-of-code
version: 0.1.0.0
license: MIT

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base

executables:
  day-01-exe:
    main: Main.hs
    source-dirs: app/Day01
    dependencies:
      - advent-of-code

library:
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Spec.hs
    source-dirs: test
    when:
      - condition: false
        other-modules: Paths_advent_of_code
    dependencies:
      - advent-of-code
      - hspec
      - hspec-discover
