name: advent-of-code
version: 0.1.0.0
github: "raphaelmeyer/advent-of-code-2015"
license: MIT

ghc-options:
  - -Wall
  - -Werror
  - -O2

dependencies:
  - base
  - containers
  - text

executables:
  aoc:
    main: Main.hs
    source-dirs: app/AoC
    dependencies:
      - advent-of-code
      - optparse-applicative

library:
  source-dirs: src
  dependencies:
    - bytestring
    - bytestring-conversion
    - cryptohash-md5
    - text

tests:
  test:
    main: Spec.hs
    source-dirs: test
    when:
      - condition: false
        other-modules: Paths_advent_of_code
    dependencies:
      - advent-of-code
      - hspec
      - hspec-discover
